name: translate_engine_sogou
description:
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.5
  http: ^0.12.2
  translate_client:
    path: ../translate_client

dev_dependencies:
  test: ^1.0.0
